<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cookiebot"
 *
 * Auto generated by Extension Builder 2019-10-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Cookiebot',
    'description' => 'Implement cookiebot in TYPO3',
    'category' => 'plugin',
    'author' => 'Matthias Pruy',
    'author_email' => 'dev@mjpr.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-10.2.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
